### ISSUE TITLE
ELK dashboards

### ISSUE THREAD

**Issue by krabar** [mulesoft-catalyst/metrics-framework-m4#37]
Hi, in some of the ELK dashboard files not all index pattern IDs are replaced with <YOUR-INDEX-PATTERN-ID> placeholder.

Affected files:
DesignCenterDashboard.ndjson
ExchangeDashboard.ndjson
RMNetworkDashboard.ndjson
RMProdCloudhubDashboard.ndjson

**Comment by DavoCoder** [comment]
This has been fixed (develop branch) - will be available as part of the 1.4.0 release. Thanks for reporting it
